### PR TITLE
Fixed minor typo

### PR DESCRIPTION
**Pull request by gastaldi**
I also don't think "super-heroes" should be hyphenated

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks, I will republish the content shortly.

**Comment by gastaldi** [comment]
Can you also fix the public URL? https://quarkus.io/quarkus-workshops/super-heros/ should end with `heroes`

**Comment by cescoffier** [comment]
This URL works for me. Where did you find a broken link?

**Comment by gastaldi** [comment]
It's not broken, it's just grammatically incorrect (heros) :)

Em Dom, 15 de dez de 2019 15:35, Clement Escoffier <notifications@github.com>
escreveu:

**Pull request merged**
