### PR TITLE
Bump to Quarkus 3.3.2

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by holly-cummins** [comment]
I wonder if we should have dependabot doing these updates? There's a `dependabot.yml,` so I don't know why @geoand got to it first. 

Also note that checking in the zip files does no harm, but it's not needed; the build generates them and checks them in, because generating them manually was annoying. :)

**Review by holly-cummins — APPROVED** [review]

**Comment by geoand** [comment]
Good point!

**Comment by geoand** [comment]
Good point, I'll bump

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Merging before 3.3.3 to be released 😀

**Pull request merged**
