### PR TITLE
use mutiny instead of Java rx

### PR DESCRIPTION
**Pull request by aureamunoz**
Related to #76

Hi, this is a first try to use mutiny, I'm a little lost because I don't have a lot of experience with reactive and I don't get to make it work, I don't see statistics move when new fights are triggered.
Could you please take a look and give me some feedback, @agoncal @cescoffier ?

### CODE REVIEW

**Comment by aureamunoz** [comment]
I need still to work on WebSocket classes :woman_facepalming: :grin: :grin:

**Comment by aureamunoz** [comment]
Also, I have to refactor the instructions in order to integrate theses changes

**Comment by cescoffier** [comment]
Where are we about this one?
Should I take a look?

**Comment by aureamunoz** [comment]
If you want. I wanted to investigate and debug more but have not had the time yet. If no rush I could do it next week. To many fronts opened currently with Filomena, covid, kids.....;-)

**Comment by cescoffier** [comment]
@aureamunoz I took your commit and continued the work in https://github.com/quarkusio/quarkus-workshops/pull/87.

**Pull request merged**
