### PR TITLE
Add icons to configurator

### PR DESCRIPTION
**Pull request by holly-cummins**
I've added some icons which will hopefully (a) make the configurator look snazzy and (b) give a quick indication what the menus are for. 

I also did some styling improvements, based on suggestions from @insectengine.

### CODE REVIEW

**Comment by insectengine** [comment]
I see there is a second button at the top to go to the default workshop. I think this is confusing since the original button is specifically connected to the form to filter the content. 

I'd suggest adding the "Just take me to the default workshop" text as a simple link to the right of the button. This way folks will know the button activates the form while the link bypasses it.

**Comment by insectengine** [comment]
configure_workshop

**Review by agoncal — APPROVED** [review]
This is looking super nice !!! Congrats

**Comment by holly-cummins** [comment]
> I see there is a second button at the top to go to the default workshop. I think this is confusing since the original button is specifically connected to the form to filter the content.
> 
> I'd suggest adding the "Just take me to the default workshop" text as a simple link to the right of the button. This way folks will know the button activates the form while the link bypasses it.

You're totally right. The two buttons caused a bit of chaos in the workshop, so I raised #371. I have a PR almost ready for sorting it out, but I got a bit overexcited with some fancy css.

**Pull request merged**
