### PR TITLE
Adding missing Powers

### PR DESCRIPTION
**Pull request by agoncal**
There were a few heroes and villains that did not have powers. For the narration, it's better to have a few posers

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Speaking about power, I need merge powers 😁

**Comment by agoncal** [comment]
@geoand you can't merge on this repo ???

**Comment by geoand** [comment]
@cescoffier Can I get commit rights?

**Comment by cescoffier** [comment]
I invited you as maintainer 1h ago. Did you get the invite?

**Comment by geoand** [comment]
Ah thanks!

**Pull request merged**
