### PR TITLE
Automatically detect correct build profile (no more -Pcomplete)

### LINKED ISSUE #233: Consider making -Pcomplete profile the default and having another profile for the minimal build
I find it counter-intuitive that `mvn install` doesn't build everything. IMO, it makes it easier for regressions to slip through, and it also makes it harder for people doing the workshop to build everything. 

I updated the CI to use the `-Pcomplete` flag, so that the CI gives proper coverage (#229) . 

I'm not sure if this was the best approach, though. What problem were we trying to solve by making the default build only build a subset of the projects? Would it be better to have the default build everything, and use a profile to build a subset? 

I *think* the problem we were trying to solve is that if we declare modules in the top-level pom and they don't exist, builds will fail for people doing the project. https://stackoverflow.com/questions/4448599/maven-modules-optional-in-pom-xml has a similar question and suggests using profiles to work around the issue, exactly as we have done. 

But maybe there's another way. For example, we could use the presence of a module folder for [profile activation](https://maven.apache.org/ref/3.0.3/maven-model/maven.html#class_file). If we can remember whether multiple conditions are `and` or `or` in maven profile activation (it changed in a minor version a while ago) we can check for every file. 

Ideally I would default to doing everything and activate the subset profile based on a missing file, but I don't think profile activations support `<not>`.

### LINKED ISSUE #378: Instructions for `-Pcomplete` early in workshop cause confusion
We just had a question in the workshop from someone running with -Pcomplete and hitting a missing `assembly.xml`. If we put text in the workshop, people will tend to follow it, even if we have guards that say 'don't do this.'

We maybe should either drop the whole section, since it's a bit confusing or move it to a 'Reference' part that's listed in the toc but not quite so near the beginning. With #233, the instructions would be fairly trivial anyway.

### PR DESCRIPTION
**Pull request by holly-cummins**
Resolves #233
Resolves #378

I think the reason we originally had profiles is that depending what zip they extract, sometimes people have lots of modules, sometimes they have a small number, and maven does not allow us to define optional modules, or just do a “build all subfolders” command. 

The [mvn docs](https://maven.apache.org/guides/introduction/introduction-to-profiles.html#profile-order) say:

> All profile elements in a POM from active profiles overwrite the global elements with the same name of the POM or extend those in case of collections. In case multiple profiles are active in the same POM or external file, the ones which are defined later take precedence over the ones defined earlier (independent of their profile id and activation order).

So anything we define in a profile will add to anything we define in the main pom, but profiles won’t add to each other, and we need to define them in order. 

We can only define one ‘guard’ file per profile. The good news is that limits the combinatorics, and we have to assume a limited number of ‘profiles’ (as it were!) to cater for. This does mean if someone is midway through building the workshop and tries a top-level build, it will fail because of missing projects or, depending what guard file we choose, not build everything.

This is annoying, but no worse than where we were before. At least builds of the extracted zips will work. 

Well, they would build if it wasn’t for #280. I’ll fix that next, and also add some tests to make sure the zips can actually build, since it seems like core technical capability.

### CODE REVIEW

**Comment by holly-cummins** [comment]
It turns out there are some subtleties with reactors build order and profiles. The reason some of the instructions and readmes build the extension module first is that, under some circumstances, maven will build the deployment module of the extension quite late. It doesn't take transitive dependencies into account when deciding the reactor order. It seemed like one way of defining the profiles got the correct order, so it behaved like the old `-Pcomplete`, and the other got an incorrect order and was broken. So I've gone with the way that works, but it's a bit more fragile than is ideal.

**Comment by holly-cummins** [comment]
Another complexity - we used to only build native for the core profile in the CI, but with this change, we build it for everything. That seems like the right kind of check to be doing in the CI, but it's 

(a) slow 
(b) failing 

I've gone back to just building the core with native, and raised #404 and #405.

**Comment by agoncal** [comment]
I remember that @cescoffier had to refactor the directory structure and change the `pom` to make sure the extension was built first, and then the app in second

**Review by agoncal — APPROVED** [review]
OMG I can already see some merge conflicts when I'll create my PR ;o)

**Comment by holly-cummins** [comment]
Merging, @agoncal! The exclude for the extension version build isn't working - maybe it needs to be extension-version-parent? - but I will do that in a follow-up PR.

**Comment by agoncal** [comment]
Ok. I'll be careful with the extension then

**Comment by holly-cummins** [comment]
> Ok. I'll be careful with the extension then

I think there's no need, just be aware that the CI build is annoyingly long now (doh, sorry!), and one mitigation that looks like it's there (not doing a native build of the extension) isn't actually working. :)

**Pull request merged**
